### ISSUE TITLE
puzzles.md:9: During Resolution Phase, execute all card...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#103]
The puzzle `1-1504dc6a` from EnigmaDragons/ProjectNeon#1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/576113e803b84e8cd8475554c3f909ecbec03227/puzzles.md#L9-L9

The puzzle was created by Silas Reinagel on 17-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `1-1504dc6a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#103` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
