### ISSUE TITLE
PartyVisualizer.cs:14: Render player characters in battle...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#109]
The puzzle `28-57f60114` from EnigmaDragons/ProjectNeon#28 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/fc0a969734aa1fc771c9c2ae6b9f31caff68236b/src/ProjectNeon/Assets/Battle/Party/PartyVisualizer.cs#L14-L14

The puzzle was created by Paulo Lobo on 17-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#109](https://github.com/enigmadragons/projectneon/issues/109) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#109` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
