### ISSUE TITLE
ConfirmCardSelection.cs:5: Visually confirm player...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#112]
The puzzle `90-70ccf5b2` from EnigmaDragons/ProjectNeon#90 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/651565d545e784e67002795663dd78f952a3b097/src/ProjectNeon/Assets/Battle/Cards/ConfirmCardSelection.cs#L5-L5

The puzzle was created by Silas Reinagel on 17-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#112](https://github.com/enigmadragons/projectneon/issues/112) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#112` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
