### ISSUE TITLE
Bug: Vulnerable works too correctly with the "math" and creates unexpected outcomes.

### ISSUE THREAD

**Issue by Kazamaru** [EnigmaDragons/ProjectNeon#1149]
E.g. Slash says it does 12, I make them vulnerable and slash for 17.

**Comment by SilasReinagel** [comment]
What other effects did you have active at the time? Were you under the effects of Coordinated Attack? 

What would be the "Expected" outcome for rounding? Right now we have the math setup to error on the side of making effects bigger rather than smaller.

**Comment by Kazamaru** [comment]
I'm under so many different buff affects it's hard to keep track of. I'm usually under Coordinated Assault & Electrify Blade. 

The expected outcome is that if the card says 12 and they are vulnerable I should do 18. I've also noticed at least one case where my Grenade said it would do 11...and then did 12.

**Comment by SilasReinagel** [comment]
Vulnerable should increase the amount of damage a target takes by 1/3. So, 12 + 4 would have been 16.

We are being generous with rounding, so you get a 17 instead of a 16. Are you thinking that we should cap it to the face value, and not be generous?
