### ISSUE TITLE
EnemyVisualizer.cs:26-28: Wire enemy setup with correct...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#115]
The puzzle `29-0112573d` from EnigmaDragons/ProjectNeon#29 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/c7efcda6d4de3703ef5016d14ee9466252c95fbf/src/ProjectNeon/Assets/Battle/Enemies/EnemyVisualizer.cs#L26-L28

The puzzle was created by Paulo Lobo on 17-Sep-19. 

Estimate: 5 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/115#issuecomment-532438300))

@SilasReinagel Job [#115](https://github.com/enigmadragons/projectneon/issues/115) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `29-0112573d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#115` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#115](https://github.com/enigmadragons/projectneon/issues/115) is now out of scope
