### ISSUE TITLE
Bug: When stunned by different effects the stun can wear off more quickly than it should.

### ISSUE THREAD

**Issue by Kazamaru** [EnigmaDragons/ProjectNeon#1151]

**Comment by SilasReinagel** [comment]
Can you give more precise details? Which specific effects or cards was a character effected by? 

What was the outcome? What is the expected outcome?

**Comment by Kazamaru** [comment]
It happened when 2 different people played a stun card, so Electroblade went to 4 stun, at the start of the next turn it decayed to 2 stun, and then faded at the start of the next turn.

So turn A he got double stunned
Turn B he should be stunned
Turn C he should be stunned, but wasn't.
Turn D he shouldn't be stunned.

**Comment by SilasReinagel** [comment]
Currently, Stuns don't stack. If you get hit by multiples, the most recent one replaces the existing one. So, at the moment, this is working as designed. 

Are you wishing that it would extend the duration?

Also, this problem might go away now that enemies aren't going to double-stun the same target. I just implemented that today.
