### ISSUE TITLE
Setup Unit Testing for Project

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#118]

**Comment by SilasReinagel** [comment]
@paulodamaso Unit Tests are now added to the Project. 

They should work both in your IDE, and in the Unity Test Runner. 

Since you can't normally instantiate MonoBehavior Objects, we can create testable copies of things using the `TestableObjectFactory`.

Since `[SerializeField] private` fields can't be accessed or set from Test, Create an `Init` method that behaves like a `ctor` for testability.

**Comment by 0crat** [comment]
Job [#118](https://github.com/enigmadragons/projectneon/issues/118) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#118` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
