### ISSUE TITLE
EncounterBuilder.cs:22: Evolve Encounter Generation after...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#119]
The puzzle `52-6065c661` from EnigmaDragons/ProjectNeon#52 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/2fd3e4b91a8c0e83d34dcbbe2fe01945828d0a43/src/ProjectNeon/Assets/Enemies/EncounterBuilder.cs#L22-L22

The puzzle was created by Paulo Lobo on 18-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue
