### ISSUE TITLE
PartyVisualizer.cs:11: Dynamically create Characters from...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#130]
The puzzle `125-3109d1f9` from EnigmaDragons/ProjectNeon#125 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/99df52a6287f41b27eb3ae7e72fd452b159ddabe/src/ProjectNeon/Assets/Battle/Party/PartyVisualizer.cs#L11-L11

The puzzle was created by Silas Reinagel on 19-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `125-3109d1f9` has disappeared from the source code, that's why I closed this issue.
