### ISSUE TITLE
Once all Cards Selected, hide the hand, and move all Play Zone cards to Resolution Area

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#133]
See this video: https://youtu.be/xMrdxMn7wN0?t=164
Once Player and Enemy have selected their Cards:
- Hide the player hand.
- Move all card from the Player Play Zone to the Resolution Zone
- Resolution Zone should be visible at the bottom of the screen

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/133#issuecomment-532934021))

@SilasReinagel Job [#133](https://github.com/enigmadragons/projectneon/issues/133) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
You @whimsysoftware[/z](https://www.0crat.com/u/whimsysoftware) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by SilasReinagel** [comment]
@WhimsySoftware Can you create a PR for this?

**Comment by 0pdd** [comment]
@SilasReinagel 2 puzzles [#267](https://github.com/EnigmaDragons/ProjectNeon/issues/267), [#268](https://github.com/EnigmaDragons/ProjectNeon/issues/268) are still not solved.
