### ISSUE TITLE
DeckBuilder: Display Decklist for Selected Character

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#137]
Like Decklist on right: https://techraptor.net/wp-content/uploads/2019/04/steamworld-quest-deck-building.jpg

**Comment by 0crat** [comment]
You @whimsysoftware[/z](https://www.0crat.com/u/whimsysoftware) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#137` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by SilasReinagel** [comment]
Default 2 work units. 
Paid - 9/27
