### ISSUE TITLE
DeckBuilder: Display Icons for all Party Members. Switch Decklists on Selection

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#139]
Can be at the top of the screen like this:

https://techraptor.net/wp-content/uploads/2019/04/steamworld-quest-deck-building.jpg

**Comment by 0crat** [comment]
You @whimsysoftware[/z](https://www.0crat.com/u/whimsysoftware) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
