### ISSUE TITLE
Setup 0crat Integration

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#14]

**Comment by SilasReinagel** [comment]
Estimate: 60 minutes, role: DEV

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/14#issuecomment-529549987))

@paulodamaso This is what I know about this job in [CN3V1M4AU](https://www.0crat.com/p/CN3V1M4AU), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#14](https://github.com/enigmadragons/projectneon/issues/14) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CN3V1M4AU?q=%7Bjob%3A%27gh%3Aenigmadragons%2Fprojectneon%2314%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/14#issuecomment-529553682))

@paulodamaso Job [#14](https://github.com/enigmadragons/projectneon/issues/14) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/14#issuecomment-529553682))

@paulodamaso There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@1bed83ee-72bd-4b90-b626-859c1bf71176, thread: pool-5-thread-3
com.jcabi.github.Bulk$1$1[123] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
org.hamcrest.MatcherAssert[20] java.lang.AssertionError: HTTP response status is not equal to 200:
404 Not Found [https://api.github.com/repos/enigmadragons/projectneon/labels/scope]
Server: GitHub.com
Date: Mon, 09 Sep 2019 16:15:29 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 3880
X-RateLimit-Reset: 1568048960
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: 89B2:4DCA:191E720:3186251:5D767AA1

{"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/labels/#update-a-label"}
Expected: HTTP response with status 200
     but: was <404 Not Found [https://api.github.com/repos/enigmadragons/projectneon/labels/scope]
Server: GitHub.com
Date: Mon, 09 Sep 2019 16:15:29 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 3880
X-RateLimit-Reset: 1568048960
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: 89B2:4DCA:191E720:3186251:5D767AA1

{"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/labels/#update-a-label"}>
```

[0.49.8](https://github.com/zerocracy/farm): CID: [c86e4451-4b75-4093-ac61-aa147428553d](https://www.0crat.com/footprint/CN3V1M4AU/c86e4451-4b75-4093-ac61-aa147428553d), Type: "Job was added to WBS"

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `DEV` is banned at [#14](https://github.com/enigmadragons/projectneon/issues/14); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by SilasReinagel** [comment]
@0crat boost 2x

**Comment by 0crat** [comment]
> @0crat boost 2x ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/14#issuecomment-529593616))

@SilasReinagel Current boost factor of [#14](https://github.com/enigmadragons/projectneon/issues/14) is 2x, nothing changed

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
The job [#14](https://github.com/enigmadragons/projectneon/issues/14) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/8c108263-36be-43be-8059-d0ce0c316d00); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by SilasReinagel** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/14#issuecomment-529597961))

@SilasReinagel Boost 4x was set for [#14](https://github.com/enigmadragons/projectneon/issues/14)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/14#issuecomment-529640607))

@paulodamaso This is what I know about this job in [CN3V1M4AU](https://www.0crat.com/p/CN3V1M4AU), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#14](https://github.com/enigmadragons/projectneon/issues/14) is [in scope](http://www.zerocracy.com/policy.html#14) for 4hr
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [2hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get 100% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 60 minutes/points
  * These users are banned and won't be assigned:
    * @silasreinagel[/z](https://www.0crat.com/u/silasreinagel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CN3V1M4AU?q=%7Bjob%3A%27gh%3Aenigmadragons%2Fprojectneon%2314%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#14](https://github.com/enigmadragons/projectneon/issues/14) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +65 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#14` doesn't exist in WBS, can't create order
