### ISSUE TITLE
BattleState.cs:7: Initialize this when the Encounter is...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#141]
The puzzle `1-a7548459` from EnigmaDragons/ProjectNeon#1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/dfe1b4f184258b9cee14b942bfba8ce5856bac75/src/ProjectNeon/Assets/State/Templates/BattleState.cs#L7-L7

The puzzle was created by Silas Reinagel on 20-Sep-19. 

Estimate: 10 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/141#issuecomment-533412010))

@SilasReinagel Job [#141](https://github.com/enigmadragons/projectneon/issues/141) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job [#141](https://github.com/enigmadragons/projectneon/issues/141) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#141` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#141](https://github.com/enigmadragons/projectneon/issues/141) is now out of scope

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#272](https://github.com/EnigmaDragons/ProjectNeon/issues/272), [#273](https://github.com/EnigmaDragons/ProjectNeon/issues/273) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#286](https://github.com/EnigmaDragons/ProjectNeon/issues/286) is still not solved; solved: [#272](https://github.com/EnigmaDragons/ProjectNeon/issues/272), [#273](https://github.com/EnigmaDragons/ProjectNeon/issues/273).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#272](https://github.com/EnigmaDragons/ProjectNeon/issues/272), [#273](https://github.com/EnigmaDragons/ProjectNeon/issues/273), [#286](https://github.com/EnigmaDragons/ProjectNeon/issues/286).
