### ISSUE TITLE
BattleState.cs:10: Replace this with Member once...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#142]
The puzzle `1-d60e1d36` from #1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/dfe1b4f184258b9cee14b942bfba8ce5856bac75/src/ProjectNeon/Assets/State/Templates/BattleState.cs#L10-L10

The puzzle was created by Silas Reinagel on 20-Sep-19. 

Estimate: 10 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `1-d60e1d36` has disappeared from the source code, that's why I closed this issue.
