### ISSUE TITLE
CharacterPool.cs:6: Is this really a state structure? Is...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#143]
The puzzle `1-6bb15ff3` from #1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/dfe1b4f184258b9cee14b942bfba8ce5856bac75/src/ProjectNeon/Assets/State/Templates/CharacterPool.cs#L6-L6

The puzzle was created by Silas Reinagel on 20-Sep-19. 

Estimate: 10 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `1-6bb15ff3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#143](https://github.com/enigmadragons/projectneon/issues/143) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#143` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
