### ISSUE TITLE
Party.cs:5: change this to a dynamic size array

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#145]
The puzzle `1-59281c3f` from #1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/dfe1b4f184258b9cee14b942bfba8ce5856bac75/src/ProjectNeon/Assets/State/Templates/Party.cs#L5-L5

The puzzle was created by Silas Reinagel on 20-Sep-19. 

Estimate: 10 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@SilasReinagel just for reminding you that `Party` will be replaced by `Team` concept according to new specs, so I'd avoid to change anything at it until we have #54 merged

**Comment by SilasReinagel** [comment]
@paulodamaso Sounds great. I haven't put this ticket in scope yet. Maybe we won't even need it.
