### ISSUE TITLE
SelectCardTargets.cs:48: Get Possible Targets,as per Card...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#148]
The puzzle `1-063bd082` from EnigmaDragons/ProjectNeon#1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/f2072051f2e9355d46b9d008f924132e1e007050/src/ProjectNeon/Assets/Features/Battle/Cards/SelectCardTargets.cs#L48-L48

The puzzle was created by Silas Reinagel on 20-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/148#issuecomment-533412463))

@SilasReinagel Job [#148](https://github.com/enigmadragons/projectneon/issues/148) is now in scope, role is `DEV`

**Comment by SilasReinagel** [comment]
This one is now only 15 minutes of work, since the codebase has evolved since it was created.

**Comment by 0pdd** [comment]
The puzzle `1-063bd082` has disappeared from the source code, that's why I closed this issue.
