### ISSUE TITLE
Setup Unity CI Build

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#15]
Estimate: 30 minutes, role: DEV.

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/15#issuecomment-530088852))

@SilasReinagel Job [#15](https://github.com/enigmadragons/projectneon/issues/15) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by paulodamaso** [comment]
@SilasReinagel Which CI provider/ toll you want us to use in project?

**Comment by SilasReinagel** [comment]
@paulodamaso Preference is Github Actions.

If that’s not possible, then Appveyor.

**Comment by paulodamaso** [comment]
@SilasReinagel But what should I do? We don't have automated tests and the compilation and execution of the game is handled by the unity IDE. How could I execute it in an automated way?

**Comment by SilasReinagel** [comment]
@paulodamaso How about researching Unity Cloud Build?

https://learn.unity.com/tutorial/unity-cloud-build#5c7f8528edbc2a002053b45b

There might be other options too. How about you create a proposal for how we can do this with a couple options, and then open a puzzle for setting it up?

**Comment by 0crat** [comment]
The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#15](https://github.com/enigmadragons/projectneon/issues/15), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) everybody who has role `DEV` is banned at [#15](https://github.com/enigmadragons/projectneon/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
