### ISSUE TITLE
Create Mathematical Justification for Cards Draft

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#150]
All cards should be flavorful while being mathematically viable. The draft will be modified in actual testing.
On a spreadsheet all status effects should have a numeric value, all modifiers have a multiplicative justification, etc.

**Comment by 0crat** [comment]
The job [#150](https://github.com/enigmadragons/projectneon/issues/150) assigned to @kazamaru[/z](https://www.0crat.com/u/kazamaru), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/335e43b8-8ef6-4bf0-9cf5-1c7da84d16a9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @kazamaru[/z](https://www.0crat.com/u/kazamaru) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
@kazamaru[/z](https://www.0crat.com/u/kazamaru) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
