### ISSUE TITLE
Pyro is always greyed out (unselectable without arrow keys)

### ISSUE THREAD

**Issue by MichaelElkan** [EnigmaDragons/ProjectNeon#1526]

**Comment by SilasReinagel** [comment]
@MichaelElkan Do you have more details on this scenario?

I can't recreate this. I was able to select the Pyromancer and play cards with with mouse and arrow keys.

**Comment by MichaelElkan** [comment]
In my most recent test he wasn't greyed out anymore. In this screenshot you cant see my mouse but it was hovering over the pyro and the arrow wasn't moving.
![image](https://user-images.githubusercontent.com/12078012/97809900-04434680-1c3e-11eb-8bae-0c8b729ddb24.png)

**Comment by MichaelElkan** [comment]
Same issue here even when he is in a different slot

![image](https://user-images.githubusercontent.com/12078012/97809965-859ad900-1c3e-11eb-9155-cb9214db960c.png)

**Comment by MichaelElkan** [comment]
oh looks like pyro was greyed out in the most recent screenshot I sent
