### ISSUE TITLE
SpecificEncounterSegment.cs:13: Setup Custom Encounter,...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#159]
The puzzle `1-dc32693b` from EnigmaDragons/ProjectNeon#1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/76ba10e0cc7caefa416b542caf9f4b10a2555c1c/src/ProjectNeon/Assets/Features/GameProgression/SpecificEncounterSegment.cs#L13-L13

The puzzle was created by Silas Reinagel on 20-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/159#issuecomment-533435301))

@SilasReinagel Job [#159](https://github.com/enigmadragons/projectneon/issues/159) is now in scope, role is `DEV`

**Comment by paulodamaso** [comment]
@SilasReinagel It isn't clear what kind of setup we need to do in Custom Encounter.

**Comment by SilasReinagel** [comment]
The enemies in the Specific Encounter should be setup in the Enemy Area for the battle.
