### ISSUE TITLE
puzzles.md:10: Rebuild Victory and Defeat Scenes using...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#167]
The puzzle `1-4d1459e0` from #1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/11b2ea5b4e310fb6b6a98448beb0370e9df2e261/puzzles.md#L10-L10

The puzzle was created by Silas Reinagel on 21-Sep-19. 

Estimate: 20 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue
