### ISSUE TITLE
something causes a bunch of turn skips to happen

### ISSUE THREAD

**Issue by ZavixDragon** [EnigmaDragons/ProjectNeon#1695]
its noticable when you apply on start of turn effects and then randomly multiple turns will go by trigger the effects multiple times

boss and three party members are present when its occuring
it appears like it doesn't trigger when watched so probably race condition
playing at times 4 speed
using keyboard controls

**Comment by SilasReinagel** [comment]
This has got to be the worst bug ticket title I have seen in a long time.

If there are no reproduction steps, I'm planning to archive this card. It's impossible to troubleshoot.

The comments don't look remotely related to the title issue.
