### ISSUE TITLE
Adventure.cs:8: Design. What happens when the adventure...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#170]
The puzzle `1-1643e10c` from EnigmaDragons/ProjectNeon#1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/94daa92f329c5fa5fd240a426fc5252223c2dcc4/src/ProjectNeon/Assets/Features/GameProgression/Adventure.cs#L8-L8

The puzzle was created by Silas Reinagel on 21-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue
