### ISSUE TITLE
Member.cs:5: We have a circular reference between Member...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#185]
The puzzle `1-5a608957` from EnigmaDragons/ProjectNeon#1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/c48e7bdc6b3393a73d48fc67509149995d1e8062/src/ProjectNeon/Assets/Data/Templates/Member.cs#L5-L5

The puzzle was created by Silas Reinagel on 24-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `1-5a608957` has disappeared from the source code, that's why I closed this issue.
