### ISSUE TITLE
Battle: After Setup is Complete, each Enemy should choose cards and put them in a Card Resolution Zone

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#190]
Once all enemies have selected their PlayedCards, a `EnemyTurnsConfirmed` event should be published.

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by SilasReinagel** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/190#issuecomment-534620717))

@SilasReinagel Job [#190](https://github.com/enigmadragons/projectneon/issues/190) is already in scope

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/190#issuecomment-534621263))

@SilasReinagel The job [#190](https://github.com/enigmadragons/projectneon/issues/190) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/eac1b71f-f32d-4363-b090-29f6ed68f580); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#195](https://github.com/EnigmaDragons/ProjectNeon/issues/195) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 7 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#190](https://github.com/enigmadragons/projectneon/issues/190) is now out of scope

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#195](https://github.com/EnigmaDragons/ProjectNeon/issues/195) is solved here.
