### ISSUE TITLE
BattleState.cs:15-17: We need references to Member Decks...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#193]
The puzzle `55-0d6ba60f` from EnigmaDragons/ProjectNeon#55 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/f96426c2f6417d02ddfc91dee24e257645b04cb9/src/ProjectNeon/Assets/State/Templates/BattleState.cs#L15-L17

The puzzle was created by Paulo Lobo on 24-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
We need references to Enemy Decks, but not to Member decks. This game isnt' about Deck manipulations.

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#193` is not assigned, can't get performer
