### ISSUE TITLE
EnemyCardSelection.cs:14-15: Refactor the relation Member...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#195]
The puzzle `190-6706b496` from EnigmaDragons/ProjectNeon#190 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/7aabee3b0e34b5c4d7dcec18a2fb7056bd74838a/src/ProjectNeon/Assets/Features/Battle/Cards/EnemyCardSelection.cs#L14-L15

The puzzle was created by Paulo Lobo on 24-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#195](https://github.com/enigmadragons/projectneon/issues/195) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/c316df7e-261a-4ee9-991f-28166984d784); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `190-6706b496` has disappeared from the source code, that's why I closed this issue.
