### ISSUE TITLE
Bug: Customize Deck and Saving it Advances the Adventure

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#201]
Work Size: 1 unit (15 min)

**Comment by paulodamaso** [comment]
@SilasReinagel Isn't that supposed to work this way? After we customize the deck and save it, it would move to `GameScene` right?

**Comment by SilasReinagel** [comment]
@paulodamaso Yes. But right now, whenever you return to the `GameScene`, it thinks the next Segment of the Adventure has been finished. This isn't true if we edited the deck. See `SelectNextStageSegment.cs`
