### ISSUE TITLE
SelectCardTargets.cs:50: Needs to know who Self is, if...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#205]
The puzzle `1-5091fbb9` from EnigmaDragons/ProjectNeon#1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/b2cdc09c7b448a0b29cb5845ba1156a1aa32d223/src/ProjectNeon/Assets/Features/Battle/Cards/SelectCardTargets.cs#L50-L50

The puzzle was created by Silas Reinagel on 26-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by SilasReinagel** [comment]
The puzzle was opened at 1 unit size, but correctly solving this, probably by setting a fixed performer to a card will involve some work.

This one will pay 2 units.
