### ISSUE TITLE
High-Level Design - 3rd Character Class

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#21]
Class should have three basic mechanic types. (i.e. Rifles, Healing, Tanking, Buffing, Hacking, Environment Effects, Grenades, Magic, Tech Gadgets, Summoning, etc)

Document the basic concept of the class, with brief descriptions about their three core mechanics.

Role: DESIGN
Estimate: 30 minutes

**Comment by 0crat** [comment]
You @kazamaru[/z](https://www.0crat.com/u/kazamaru) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#21` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
