### ISSUE TITLE
PlayedCard.cs:22-25: We need a better solution to link...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#212]
The puzzle `207-45902ab0` from #207 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/6010c620cce49f5c97b59e96482b65106ff479f9/src/ProjectNeon/Assets/Features/Battle/Cards/PlayedCard.cs#L22-L25

The puzzle was created by Paulo Lobo on 26-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by SilasReinagel** [comment]
This may not be necessary. Since Cards are data and Selections are runtime only, there may be no problem with the current solution.

**Comment by 0pdd** [comment]
The puzzle `207-45902ab0` has disappeared from the source code, that's why I closed this issue.
