### ISSUE TITLE
DeckBuilder: Decklist displays current hero deck

### ISSUE THREAD

**Issue by WhimsySoftware** [EnigmaDragons/ProjectNeon#216]
When in the Deck Builder screen, the currently selected Hero's decklist should be linked to the DeckList UI elements.

**Comment by SilasReinagel** [comment]
Work Size: 2 Units

**Comment by 0pdd** [comment]
@WhimsySoftware 2 puzzles [#263](https://github.com/EnigmaDragons/ProjectNeon/issues/263), [#264](https://github.com/EnigmaDragons/ProjectNeon/issues/264) are still not solved.

**Comment by 0pdd** [comment]
@WhimsySoftware all 2 puzzles are solved here: [#263](https://github.com/EnigmaDragons/ProjectNeon/issues/263), [#264](https://github.com/EnigmaDragons/ProjectNeon/issues/264).
