### ISSUE TITLE
High-Level Design: General Game Mechanics/Effects

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#22]
Create a list of all basic effect types that might appear on card. (X Damage, X% Damage, X Heal, Apply X Debuff for X Turns, Apply X Buff for X Turns, etc.)

List should have at least 10-25 different types of effects.

Role: DESIGN
Estimate: 30 minutes

**Comment by 0crat** [comment]
You @kazamaru[/z](https://www.0crat.com/u/kazamaru) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
You @kazamaru[/z](https://www.0crat.com/u/kazamaru) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#22` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
