### ISSUE TITLE
High-Level Design: Party Upgrade Path Ideas

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#23]
Write up some a pathway of progression/choices that will happen through a playthrough.

List the kinds of choices that will happen, and at which point in the run.

Example:
Game Start: Select Party of 3
Lv2: Select new Focus Card for Character
Lv3: Select Permanent Stat Upgrade
Final Mission: Select from three battle strategies before fight starts
Game Victory: Select 1 Permanent Unlockable Bonus

Role: DESIGN
Estimate: 30 minute

**Comment by 0crat** [comment]
You @kazamaru[/z](https://www.0crat.com/u/kazamaru) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#23` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
