### ISSUE TITLE
DeckBuilderState.cs:23-24: We need to correctly...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#263]
The puzzle `216-2b2509e5` from EnigmaDragons/ProjectNeon#216 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/22748d8d6d5eaeb27cc096aa300642692a43ccde/src/ProjectNeon/Assets/Features/DeckBuilder/Scripts/DeckBuilderState.cs#L23-L24

The puzzle was created by Paulo Lobo on 02-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html). 

Work Size: 3 unit (45 min)

**Comment by WhimsySoftware** [comment]
@SilasReinagel let me know if I can take this task

**Comment by SilasReinagel** [comment]
@WhimsySoftware Sure. As long as no more than 2 PRs are open at a time right now, you can grab whichever tasks you want from this column.

**Comment by WhimsySoftware** [comment]
@SilasReinagel PR has been updated.

**Comment by WhimsySoftware** [comment]
@SilasReinagel 
Is everything correct in this ticket?
