### ISSUE TITLE
Battle Setup: 1. Shuffle player deck, and each individual enemy deck

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#27]
Role: DEV

**Comment by 0crat** [comment]
The job [#27](https://github.com/enigmadragons/projectneon/issues/27) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
