### ISSUE TITLE
Battle Setup: Player's party characters are shown on the left-side of the screen in traditional JRPG battle view

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#28]
Use greybox character squares for now, or placeholder images.

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#109](https://github.com/EnigmaDragons/ProjectNeon/issues/109) is still not solved.

**Comment by 0crat** [comment]
The job [#28](https://github.com/enigmadragons/projectneon/issues/28) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#109](https://github.com/EnigmaDragons/ProjectNeon/issues/109) is solved here.
