### ISSUE TITLE
Obsolete: DeckBuilder: Add/Remove Cards From Current Deck

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#283]
Clicking on a card in the main pane, should add a copy to the Deck list.

Clicking on a card in the Decklist should remove one copy of that card, and put a copy back in the Main Pane.

Deck changes should persist. 

Estimate: 2 units

**Comment by ZavixDragon** [comment]
This ticket seems obsolete this is already the functionality unless you are modifying a immutable deck, which are the starter decks
