### ISSUE TITLE
DeckBuilder: Require all Decks to have 12 Cards

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#284]
Deck Size should be set as a IntVariable Scriptable object.

From the DeckBuilder screen, the player should not be able to leave the DeckBuilder or to switch active Characters, unless the current deck contains the required number of cards.

An error message should be displayed on Screen if the player attends to do this.

Estimate: 2 units

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#319](https://github.com/EnigmaDragons/ProjectNeon/issues/319) is still not solved.

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#319](https://github.com/EnigmaDragons/ProjectNeon/issues/319) is solved here.
