### ISSUE TITLE
Battle Setup: Enemy characters are shown on the right-right of the screen in traditional JRPG battle view

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#29]
Role: DEV

Must trigger upon `BattleSetupStarted`
Must place them in a nice layout, even with 1-5 characters.
Must align with background.
Must broadcast event when finished like `BattleSetupEnemyPartyEntered` or similar

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#115](https://github.com/EnigmaDragons/ProjectNeon/issues/115) is still not solved.

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#115](https://github.com/EnigmaDragons/ProjectNeon/issues/115) is solved here.
