### ISSUE TITLE
Battle Setup: Player visibly draws a hand of 6 cards from his deck

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#30]
Can use greybox cards or placeholders for now.

Should slide-in from the right side of the screen.

Cards should be spaced so that all are visible. 

Estimate: 30 minutes

**Comment by 0crat** [comment]
The job [#30](https://github.com/enigmadragons/projectneon/issues/30) assigned to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/f30bc6d8-8614-47e0-8385-203de6032374); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0pdd** [comment]
@SilasReinagel 4 puzzles [#78](https://github.com/EnigmaDragons/ProjectNeon/issues/78), [#79](https://github.com/EnigmaDragons/ProjectNeon/issues/79), [#80](https://github.com/EnigmaDragons/ProjectNeon/issues/80), [#81](https://github.com/EnigmaDragons/ProjectNeon/issues/81) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#30](https://github.com/enigmadragons/projectneon/issues/30) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0pdd** [comment]
@SilasReinagel 3 puzzles [#79](https://github.com/EnigmaDragons/ProjectNeon/issues/79), [#80](https://github.com/EnigmaDragons/ProjectNeon/issues/80), [#81](https://github.com/EnigmaDragons/ProjectNeon/issues/81) are still not solved; solved: [#78](https://github.com/EnigmaDragons/ProjectNeon/issues/78).

**Comment by 0pdd** [comment]
@SilasReinagel 2 puzzles [#79](https://github.com/EnigmaDragons/ProjectNeon/issues/79), [#80](https://github.com/EnigmaDragons/ProjectNeon/issues/80) are still not solved; solved: [#78](https://github.com/EnigmaDragons/ProjectNeon/issues/78), [#81](https://github.com/EnigmaDragons/ProjectNeon/issues/81).

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#79](https://github.com/EnigmaDragons/ProjectNeon/issues/79) is still not solved; solved: [#78](https://github.com/EnigmaDragons/ProjectNeon/issues/78), [#80](https://github.com/EnigmaDragons/ProjectNeon/issues/80), [#81](https://github.com/EnigmaDragons/ProjectNeon/issues/81).

**Comment by 0pdd** [comment]
@SilasReinagel all 4 puzzles are solved here: [#78](https://github.com/EnigmaDragons/ProjectNeon/issues/78), [#79](https://github.com/EnigmaDragons/ProjectNeon/issues/79), [#80](https://github.com/EnigmaDragons/ProjectNeon/issues/80), [#81](https://github.com/EnigmaDragons/ProjectNeon/issues/81).
