### ISSUE TITLE
Battle: Create placeholder card that deals 10 damage and integrate with battle system.

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#31]
Must have Name, Description Text and working Effect.

Must be able to put 8 of these in a Player Character deck.

**Comment by 0crat** [comment]
The job [#31](https://github.com/enigmadragons/projectneon/issues/31) assigned to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/bf9334c8-7dd2-4a5b-a953-5644160d8141); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0pdd** [comment]
@SilasReinagel 3 puzzles [#84](https://github.com/EnigmaDragons/ProjectNeon/issues/84), [#85](https://github.com/EnigmaDragons/ProjectNeon/issues/85), [#86](https://github.com/EnigmaDragons/ProjectNeon/issues/86) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#31](https://github.com/enigmadragons/projectneon/issues/31) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0pdd** [comment]
@SilasReinagel 2 puzzles [#84](https://github.com/EnigmaDragons/ProjectNeon/issues/84), [#85](https://github.com/EnigmaDragons/ProjectNeon/issues/85) are still not solved; solved: [#86](https://github.com/EnigmaDragons/ProjectNeon/issues/86).

**Comment by 0pdd** [comment]
@SilasReinagel all 3 puzzles are solved here: [#84](https://github.com/EnigmaDragons/ProjectNeon/issues/84), [#85](https://github.com/EnigmaDragons/ProjectNeon/issues/85), [#86](https://github.com/EnigmaDragons/ProjectNeon/issues/86).
