### ISSUE TITLE
BattleScene:  After Resolving Cards Finish Turn and Start Next Turn

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#311]
Once all card have been resolved, proceed to BattleTurnWrapUp phase.

Once all BattleTurnWrapUp steps have been completed, start a new Turn.

Ensure that once a new turn has started, player can play new card from his hand. 

Size: 2 units

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#333](https://github.com/EnigmaDragons/ProjectNeon/issues/333) is still not solved.

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#333](https://github.com/EnigmaDragons/ProjectNeon/issues/333) is solved here.
