### ISSUE TITLE
Enemy Cards Character Design Issue

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectNeon#3777]
The enemies have three notable design styles which don't go well together, makes them look like they are from 3 different games.
Type 1 : (Blurry and rustic cartoony)
![image](https://user-images.githubusercontent.com/56066524/131245503-e21a3f91-8ea7-4c12-8c1d-50dde9947590.png)
![image](https://user-images.githubusercontent.com/56066524/131245506-355e60ee-cae5-4034-b5d4-75b5f191cef7.png)
Type 2 : (Sharp and crisp)
![image](https://user-images.githubusercontent.com/56066524/131245521-756cd62a-b851-4c2b-8f46-26bdff6ab6bb.png)
![image](https://user-images.githubusercontent.com/56066524/131245579-1ff4781e-3b8b-44f1-8d4c-467c18d76cb4.png)
Type 3 : (Detailed and semi realistic)
![image](https://user-images.githubusercontent.com/56066524/131245610-55ae23e5-37cd-42a5-9d36-053bb29ada1f.png)

**Comment by SilasReinagel** [comment]
All the enemies are placeholder art, currently. 

We are still budgeting for all Enemy Art. That scope of work is in the future.
