### ISSUE TITLE
Character Card Description Text Issue

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectNeon#3785]
Some sentences in the cards have a weird bounce/wobble effect. Is this intentional? 
![image](https://user-images.githubusercontent.com/56066524/131246465-0d0d6f9c-a7ac-4bf2-bdea-f8a334f3aa52.png)
![image](https://user-images.githubusercontent.com/56066524/131246484-7e0e3084-8a74-492d-a22a-da407c97bd2f.png)

**Comment by SilasReinagel** [comment]
@mustucontractor What resolution or settings are you seeing this?

I see this at some resolutions, but not 1920x1080
