### ISSUE TITLE
Level Select Animation Issue

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectNeon#3787]
When I selected the mission marked as 'C', The character moved from point 'A' till halfway and stopped at point 'B' and showed the mission card instead of going all the way to point 'C' and then displaying the mission card.
![image](https://user-images.githubusercontent.com/56066524/131246665-4e47971c-459a-45c3-922b-66e7ce95ac60.png)

**Comment by SilasReinagel** [comment]
This is working as intended. 

You encountered a Story Event en route to your target node.

This work precisely how it does in games like Griftlands, etc.
