### ISSUE TITLE
Card Hovers - Freaking Out in Non-Standard Resolution/Aspect Ratio

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectNeon#3789]
Taking your cursor to the bottom of the cards during battle makes the cards freak out.

**Comment by SilasReinagel** [comment]
@mustucontractor Do you have a screenshot of the video so that we can verify/reproduce the specific movement you aren't happy with?

**Comment by mustucontractor** [comment]
Having the cursor at the bottom red marked region makes the cards freak out 
![image](https://user-images.githubusercontent.com/56066524/131446252-10bed995-fd04-4f67-9636-cd66d8373519.png)

**Comment by SilasReinagel** [comment]
@mustucontractor What screen resolution do you have? I can't reproduce this at 1920x1080.
