### ISSUE TITLE
Battle Gameplay Bug

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectNeon#3802]
I finished playing my 3 cards but the enemies aren't playing their cards. 
![image](https://user-images.githubusercontent.com/56066524/131450092-0fe3ae65-fb88-49b1-82b2-9b503ac1c912.png)

**Comment by SilasReinagel** [comment]
This is not a bug. You have a playable Quick card still in hand that you may wish to play.

**Comment by mustucontractor** [comment]
I tried using all the three cards and also tried discarding it but it did not work. I had to press End Turn to continue.

**Comment by SilasReinagel** [comment]
The UI is showing that Energy Manipulation is still playable.
