### ISSUE TITLE
Enemy Cards Nerfed

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectNeon#3806]
A lot of enemy cards feel really overpowered especially for the first 5 battles where players are familiarising themselves with the game. probably best to nerf the damage and attributes.

**Comment by SilasReinagel** [comment]
@mustucontractor This needs more specifics

Is this just a generalized complaint about difficulty, or are there specific cards that you believe are overpowered? If so, which cards?
