### ISSUE TITLE
UI Card Addition & Removal Feature

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectNeon#3809]
Add a button or a feature in the UI that displays how to remove /add a card from a deck. At the moment, clicking on a card adds it to the deck but a better and more UI friendly solution would be to add a '+' on the card to add it to the deck and a 'x' to remove it from the deck. 

![image](https://user-images.githubusercontent.com/56066524/131455070-f4193cf3-1ba8-4275-ac88-e2a6487bbed0.png)

**Comment by SilasReinagel** [comment]
I'll research this idea and compare with other card games. Then we will decide
