### ISSUE TITLE
puzzles.md:7: Wire start game, exit game and options...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#40]
The puzzle `6-97d39b79` from #6 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/4e4d595a933a314d81f9b735f3a8c39584009187/puzzles.md#L7-L7

The puzzle was created by Paulo Lobo on 10-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso), @silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue
