### ISSUE TITLE
puzzles.md:8: Set up buttons and label styles in title...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#41]
The puzzle `6-db9ec73d` from EnigmaDragons/ProjectNeon#6 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/4e4d595a933a314d81f9b735f3a8c39584009187/puzzles.md#L8-L8

The puzzle was created by Paulo Lobo on 10-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso), @silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `6-db9ec73d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#41` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
