### ISSUE TITLE
Create event logic for card effects

### ISSUE THREAD

**Issue by paulodamaso** [EnigmaDragons/ProjectNeon#428]
Create event logic for card effects. We should be able to trigger card effects when some events are activated (OnAttack, etc)

**Comment by SilasReinagel** [comment]
@paulodamaso The intent of this ticket is unclear.

Precisely what behaviors would be delivered in this ticket?

**Comment by paulodamaso** [comment]
@SilasReinagel We should be able to trigger card effects asynchronously. For example, for `Aura of Retribution` card, we need to trigger some effect each time an ally is attacked. The intent of this issue is to provide this messaging system so we could set up card effects to execute when some specific conditions happen.

**Comment by SilasReinagel** [comment]
@paulodamaso Are there features that are needed for this that won't be covered by EnigmaDragons/ProjectNeon#429 ?

**Comment by paulodamaso** [comment]
@SilasReinagel This can be closed
