### ISSUE TITLE
BattleTurnWrapUpPhase.cs:3: Kill this class. Replace with...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#435]
The puzzle `1-d894fbb7` from EnigmaDragons/ProjectNeon#1 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/c1b904edaf751bde1a20961066a41913e10c0735/src/ProjectNeon/Assets/Scripts/BattleTurnWrapUpPhase.cs#L3-L3

The puzzle was created by Silas Reinagel on 30-Oct-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by SilasReinagel** [comment]
Size: 1 unit
