### ISSUE TITLE
Implement Stun Effect for Party

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#436]
The puzzle `380-a7852436` from EnigmaDragons/ProjectNeon#380 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/c1b904edaf751bde1a20961066a41913e10c0735/src/ProjectNeon/Assets/Features/Combatants/MemberState.cs#L59-L60

The puzzle was created by Silas Reinagel on 30-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
@SilasReinagel This is how I see that stun status is supposed to work:
- Player character: characters which are stunned can't play any card while being stunned, so the UI won't show any card for that character on player hand, or will show them but make them unselectable / unplayable
- Enemy character: the enemy character does not play any card when supposed to (`TurnAI.Play()` is bypassed or produce no card for that character)
Is this right or I am missing something?

**Comment by SilasReinagel** [comment]
Members can accumulate Stun Counters.

If Enemy Is Stunned and goes to resolve his card, it should fizzle and remove one Stun Counter.
At the end of a Player's Turn, each Party member should lose 1 Stun Counter.
A player may not play cards for Heroes who are Stunned.
