### ISSUE TITLE
Create composable Effect execution restrictions

### ISSUE THREAD

**Issue by paulodamaso** [EnigmaDragons/ProjectNeon#451]
We currently don't have a composable way to limit effects execution. For example, we can't compose an effect that will be executed only one time, or during seven turns. These decorators need to be created so we can implement correctly these effects.

We need two classes: one for manage effects that are based on time (turns) and other to manage effects there are executed just a finite number of times.

**Comment by SilasReinagel** [comment]
Size: 2 Units
