### ISSUE TITLE
Implement Attack concept

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#454]
Currently we are using `Attack` to represent an attack made by someone, but this implementation needs to be refactored. `Attack` should be treated as an `Effect` which causes `Physical Damage` on the target,
based on the performer stats.

The `Apply` method must send a message that an `Attack` is being performed; this message will trigger all `OnAttack` effects

**Comment by SilasReinagel** [comment]
Size Boosted by 1 unit.

New Size: 2 units.

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#460](https://github.com/EnigmaDragons/ProjectNeon/issues/460) is still not solved.

**Comment by GraphicEdit** [comment]
its throw an error

![image.png](https://zube.io/files/enigmadragons/19036281d2c8317f54f10b72355a7c27-image.png)

**Comment by SilasReinagel** [comment]
@GraphicEdit It should be fixed now in master.

If you have a problem like this in the future, go ahead and open a Bug ticket, and we'll fix it as soon as possible. 

Sorry for the inconvenience!

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#460](https://github.com/EnigmaDragons/ProjectNeon/issues/460) is solved here.
