### ISSUE TITLE
Astromancer Card - Blinding Light

### ISSUE THREAD

**Issue by paulodamaso** [EnigmaDragons/ProjectNeon#468]
Create Astromancer card Blinding Light, with the necessary effects and tests
**Blinding Light** 
Cost: 1 Mana 
Effect: Deal 3 damage to all characters. All characters deal -5 damage this turn. 
Type: Tactical
Feed-Lunar: This spell costs no mana. - conditional effect

**Comment by SilasReinagel** [comment]
Size: 2 units
