### ISSUE TITLE
Create Astromancer card Starlight, its effects and tests

### ISSUE THREAD

**Issue by paulodamaso** [EnigmaDragons/ProjectNeon#476]
**Starlight** 
Cost: 1 Mana 
Effect: Deal 5 to all enemies. 
Type: Offensive
Feed-Solar: +10% spell Power for each enemy hit by Starlight.

**Comment by SilasReinagel** [comment]
Size: 3 units

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/476#issuecomment-595216659))

@paulodamaso Job `gh:enigmadragons/projectneon#476` is not assigned, can't get performer
