### ISSUE TITLE
puzzle.md:7: Set up buttons and label styles in game scene.

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#49]
The puzzle `7-936c3be5` from #7 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/c2aca873b6fd952ce10602916795889ea5871337/puzzle.md#L7-L7

The puzzle was created by Paulo Lobo on 11-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `7-936c3be5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#49` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
