### ISSUE TITLE
Encounter Builder being flexible is better for first enemies selections, but with it's final choices it should try to hit the difficulty target better when possible

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#4937]
![image.png](https://zube.io/files/enigmadragons/2cee137f9210df43fa590d759e2a38bf-image.png)

**Comment by ZavixDragon** [comment]
more enemies will increase this accuracy, but aiming for it more will make the encounters less varied and more boring
