### ISSUE TITLE
Backend: Create Enemy Scriptable Objects

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#51]
Must be able to create an enemy from the Editor.
Enemy should have a Name.
Enemy should have a Deck.
Enemy should have a Turn AI.
Enemy should have CharacterStats.

Create of these other Scriptable objects that are missing. Ensure editor support for all of them.

**Comment by 0crat** [comment]
The job [#51](https://github.com/enigmadragons/projectneon/issues/51) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/4d55140d-8be9-4951-b933-bdd85ba1bd01); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#51](https://github.com/enigmadragons/projectneon/issues/51) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
