### ISSUE TITLE
Backend: Create Enemy Encounter Builder

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#52]
Enemy Encounter Builder should be able to create an encounter group of enemies matching a chosen difficulty value.

It must have Editor-Access to a set of possible Enemies.
Using those enemies, it must build any group that closely matches a selected difficulty value.
The encounter group must be spawned into the scene.

Should publish `BattleEnemiesSpawned` event on completion.

**Comment by 0crat** [comment]
The job [#52](https://github.com/enigmadragons/projectneon/issues/52) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/0aa0a659-f741-423e-bb5f-abcf840e2729); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@SilasReinagel 2 puzzles [#119](https://github.com/EnigmaDragons/ProjectNeon/issues/119), [#120](https://github.com/EnigmaDragons/ProjectNeon/issues/120) are still not solved.

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#119](https://github.com/EnigmaDragons/ProjectNeon/issues/119) is still not solved; solved: [#120](https://github.com/EnigmaDragons/ProjectNeon/issues/120).

**Comment by 0crat** [comment]
The job [#52](https://github.com/enigmadragons/projectneon/issues/52) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
