### ISSUE TITLE
Backend: Begin Designing Composable Card Effects

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#54]
Card should be able to add custom effects.

Initially, should support basic effects like:
- Deal X damage to Single Opponent.
- Deal X damage to Every Opponent.
- Apply Buff for X Turns to target.
- Heal X HP to Single Ally.

Cards should be able to be created as Assets in the Editor. Should be able to add/remove effects.

**Comment by 0crat** [comment]
The job [#54](https://github.com/enigmadragons/projectneon/issues/54) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/853c2a64-e54d-4b76-841f-d0ad1e116e1e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by SilasReinagel** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/54#issuecomment-534187159))

@SilasReinagel Boost 4x was set for [#54](https://github.com/enigmadragons/projectneon/issues/54)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Order was finished: +60 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#54](https://github.com/enigmadragons/projectneon/issues/54) is now out of scope

**Comment by 0pdd** [comment]
@SilasReinagel 2 puzzles [#186](https://github.com/EnigmaDragons/ProjectNeon/issues/186), [#187](https://github.com/EnigmaDragons/ProjectNeon/issues/187) are still not solved.

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#186](https://github.com/EnigmaDragons/ProjectNeon/issues/186) is still not solved; solved: [#187](https://github.com/EnigmaDragons/ProjectNeon/issues/187).

**Comment by 0pdd** [comment]
@SilasReinagel all 2 puzzles are solved here: [#186](https://github.com/EnigmaDragons/ProjectNeon/issues/186), [#187](https://github.com/EnigmaDragons/ProjectNeon/issues/187).
