### ISSUE TITLE
Battle: Enemy Action Selection

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#55]
Once a turn has begun, Each enemy should select a card and any targets for his action.

Use a dumb Random AI for now. 
Ensure that solution is polymorphic, so we can replace with a better AI later. 

Once all enemies have selected their cards, trigger a "EnemyActionsSelected" event.

**Comment by 0crat** [comment]
The job [#55](https://github.com/enigmadragons/projectneon/issues/55) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/1fc0fbe9-fd65-4b72-b907-5db1be642c17); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@SilasReinagel 3 puzzles [#191](https://github.com/EnigmaDragons/ProjectNeon/issues/191), [#192](https://github.com/EnigmaDragons/ProjectNeon/issues/192), [#193](https://github.com/EnigmaDragons/ProjectNeon/issues/193) are still not solved.

**Comment by 0crat** [comment]
The job [#55](https://github.com/enigmadragons/projectneon/issues/55) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@SilasReinagel all 3 puzzles are solved here: [#191](https://github.com/EnigmaDragons/ProjectNeon/issues/191), [#192](https://github.com/EnigmaDragons/ProjectNeon/issues/192), [#193](https://github.com/EnigmaDragons/ProjectNeon/issues/193).
