### ISSUE TITLE
Battle: Update HP UI on Member Damaged

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#558]

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#582](https://github.com/EnigmaDragons/ProjectNeon/issues/582) is still not solved.

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#582](https://github.com/EnigmaDragons/ProjectNeon/issues/582) is solved here.
