### ISSUE TITLE
Soldier - Grenade Throw Animation

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#566]
We need an animation where:

1) Solider reaches a hand to his side and grabs a grenade
2) Soldier hurls the grenade into the center of the enemy area
3) The grenade should vanish on hitting the ground
4) The soldier should return to neutral stance

**Comment by GraphicEdit** [comment]
Left Hand?

**Comment by GraphicEdit** [comment]
or Gun Throw Grenade?
