### ISSUE TITLE
Backend: Setup CurrentParty, CurrentDeck, CurrentBattle, CurrentLibrary stateful Scriptable Objects and initial states

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#57]
All should be Editor-friendly.

**Comment by 0crat** [comment]
The job [#57](https://github.com/enigmadragons/projectneon/issues/57) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/7c657251-1728-4378-b43f-e9b27cd523ec); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@SilasReinagel Shouldn't the initial states of these objects be provided programatically? Deck composition, party members, Current Battle and Library are all cretaed a runtime after a match is started, not at design time

**Comment by SilasReinagel** [comment]
@paulodamaso Yes. They should be provided programmatically, and should NOT be part of the the state of the Effect ScriptableObjects.

There might be a misunderstanding. A ScriptableObject is something that permanently exists, even when the game is not running. So `CurrentBattle` and `CurrentLibrary` actually can exist even before runtime.

**Comment by 0crat** [comment]
The job [#57](https://github.com/enigmadragons/projectneon/issues/57) assigned to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/ee939d06-515e-4418-af48-560e6644d3cb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0334c878-b23d-42ae-b9e1-9cf4f1473592, thread: pool-20-thread-6
com.zerocracy.claims.ClaimIn[198] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [job, reason, cause, _parent_sig, flow, login]
```

[0.49.11](https://github.com/zerocracy/farm): CID: [26720754-63c6-4a90-9c5d-386bfdcf4551](https://www.0crat.com/footprint/CN3V1M4AU/26720754-63c6-4a90-9c5d-386bfdcf4551), Type: "Order was canceled"

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#57](https://github.com/enigmadragons/projectneon/issues/57) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)
