### ISSUE TITLE
Create Visual HP Bar, and make it reactively bindable to HP Changed Event

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#60]
Must be reactively triggered. No Update loop.
Must display MaxHP visual amount.
Must display CurrentHP visual amount.

**Comment by 0crat** [comment]
You @whimsysoftware[/z](https://www.0crat.com/u/whimsysoftware) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by SilasReinagel** [comment]
@WhimsySoftware Can you create a PR for this?
