### ISSUE TITLE
Work on Squad Selection Functionality

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#65]
- Allow cycling between Characters
- Improve character visualizations
- Allow slots two and three to be empty
- Don't allow duplicate Character selections

**Comment by 0crat** [comment]
The job [#65](https://github.com/enigmadragons/projectneon/issues/65) assigned to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/07011503-e955-40b6-8a65-d0a2247bc719); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#65](https://github.com/enigmadragons/projectneon/issues/65) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#72](https://github.com/EnigmaDragons/ProjectNeon/issues/72) is still not solved.

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#72](https://github.com/EnigmaDragons/ProjectNeon/issues/72) is solved here.
