### ISSUE TITLE
High-Level Design: Card Construction

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#67]
Create a list of all elements a card text may need to have.

Time: 30 minutes

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/67#issuecomment-531420699))

@SilasReinagel Job [#67](https://github.com/enigmadragons/projectneon/issues/67) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
You @kazamaru[/z](https://www.0crat.com/u/kazamaru) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#67` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#67](https://github.com/enigmadragons/projectneon/issues/67) is now out of scope
