### ISSUE TITLE
SquadSlot.cs:14: Implement Readonly Inspector Attributes...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#72]
The puzzle `65-64810ef3` from EnigmaDragons/ProjectNeon#65 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/868daa201017d64c75343d4ee1d7254cbf2a0b09/src/ProjectNeon/Assets/SquadSelection/SquadSlot.cs#L14-L14

The puzzle was created by Silas Reinagel on 14-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/72#issuecomment-531439556))

@SilasReinagel Job [#72](https://github.com/enigmadragons/projectneon/issues/72) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#72](https://github.com/enigmadragons/projectneon/issues/72) assigned to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/49415fc7-0b51-4ef9-9887-c42579dcbd5c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#72](https://github.com/enigmadragons/projectneon/issues/72) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)
