### ISSUE TITLE
HandViewVisualizer.cs:25: This isn't parallel-safe. Too...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#78]
The puzzle `30-a4f0a200` from EnigmaDragons/ProjectNeon#30 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/f81f85ffa4c2ade96e24aea68a7a033e689f580f/src/ProjectNeon/Assets/Battle/Cards/HandViewVisualizer.cs#L25-L25

The puzzle was created by Silas Reinagel on 15-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/78#issuecomment-531537416))

@SilasReinagel Job [#78](https://github.com/enigmadragons/projectneon/issues/78) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `30-a4f0a200` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#78](https://github.com/enigmadragons/projectneon/issues/78) is now out of scope

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#78` is not assigned, can't get performer
