### ISSUE TITLE
Create Battle Scene

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#8]
Win Button
Lose Button

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
You must be invited in order to do that, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by SilasReinagel** [comment]
@0crat boost 1x

**Comment by 0crat** [comment]
You must be invited in order to do that, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/8#issuecomment-529838188))

@g4s8 This is what I know about this job in [CN3V1M4AU](https://www.0crat.com/p/CN3V1M4AU), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#8](https://github.com/enigmadragons/projectneon/issues/8) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CN3V1M4AU?q=%7Bjob%3A%27gh%3Aenigmadragons%2Fprojectneon%238%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by SilasReinagel** [comment]
@0crat boost 1x

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/8#issuecomment-530084387))

@SilasReinagel Job [#8](https://github.com/enigmadragons/projectneon/issues/8) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat boost 1x ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/8#issuecomment-530085097))

@SilasReinagel Boost 1x was set for [#8](https://github.com/enigmadragons/projectneon/issues/8)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
The job [#8](https://github.com/enigmadragons/projectneon/issues/8) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/8c23452e-82d7-46e5-b2b4-a4fe9c92fd15); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#8](https://github.com/enigmadragons/projectneon/issues/8) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#8` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
