### ISSUE TITLE
HandViewVisualizer.cs:29: Space card out from the center,...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#80]
The puzzle `30-acf40236` from EnigmaDragons/ProjectNeon#30 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/f81f85ffa4c2ade96e24aea68a7a033e689f580f/src/ProjectNeon/Assets/Battle/Cards/HandViewVisualizer.cs#L29-L29

The puzzle was created by Silas Reinagel on 15-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/80#issuecomment-531537391))

@SilasReinagel Job [#80](https://github.com/enigmadragons/projectneon/issues/80) is now in scope, role is `DEV`
