### ISSUE TITLE
puzzles.md:6: When Single Enemy Target card is played,...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#84]
The puzzle `31-3fc792ea` from EnigmaDragons/ProjectNeon#31 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/07e94b0172777ff7b32eedb209f69966471b6a9d/puzzles.md#L6-L6

The puzzle was created by Silas Reinagel on 15-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/84#issuecomment-531540274))

@SilasReinagel Job [#84](https://github.com/enigmadragons/projectneon/issues/84) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `31-3fc792ea` has disappeared from the source code, that's why I closed this issue.
