### ISSUE TITLE
puzzles.md:7: Create Flat damage effect, which causes X...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#85]
The puzzle `31-dbeafccb` from EnigmaDragons/ProjectNeon#31 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/07e94b0172777ff7b32eedb209f69966471b6a9d/puzzles.md#L7-L7

The puzzle was created by Silas Reinagel on 15-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/85#issuecomment-531540261))

@SilasReinagel Job [#85](https://github.com/enigmadragons/projectneon/issues/85) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job `gh:enigmadragons/projectneon#85` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#85](https://github.com/enigmadragons/projectneon/issues/85) is now out of scope
