### ISSUE TITLE
puzzles.md:8: CardView must display Card Name, Art, Type...

### ISSUE THREAD

**Issue by 0pdd** [EnigmaDragons/ProjectNeon#86]
The puzzle `31-f5691d5e` from EnigmaDragons/ProjectNeon#31 has to be resolved: 

https://github.com/EnigmaDragons/ProjectNeon/blob/07e94b0172777ff7b32eedb209f69966471b6a9d/puzzles.md#L8-L8

The puzzle was created by Silas Reinagel on 15-Sep-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) please, pay attention to this issue

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/86#issuecomment-531540285))

@SilasReinagel Job [#86](https://github.com/enigmadragons/projectneon/issues/86) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#86](https://github.com/enigmadragons/projectneon/issues/86) assigned to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/d83c6d71-9b83-42d9-bfc4-5731217ac3ee); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#86](https://github.com/enigmadragons/projectneon/issues/86) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)
