### ISSUE TITLE
Battle: Player Card Selection

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#90]
Player should select cards from hand.
When a card is selected, it should be moved out of the hand, into a Turn Card zone higher on the screen.
When three cards are selected, player should be prompted to Confirm their selection.
Selected Cards should be able to be unselected. When a card is unselected, it should return to hand. 

![image.png](https://zube.io/files/enigmadragons/ca5c2d0ac4ce27bcb3749abd25f8d74d-image.png)

**Comment by SilasReinagel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/EnigmaDragons/ProjectNeon/issues/90#issuecomment-531628828))

@SilasReinagel Job [#90](https://github.com/enigmadragons/projectneon/issues/90) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
The job [#90](https://github.com/enigmadragons/projectneon/issues/90) assigned to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/960095a2-8b2f-46c8-b1bd-02c61396dd09); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#112](https://github.com/EnigmaDragons/ProjectNeon/issues/112) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#90](https://github.com/enigmadragons/projectneon/issues/90) is now out of scope

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#112](https://github.com/EnigmaDragons/ProjectNeon/issues/112) is solved here.
