### ISSUE TITLE
High-Level Design: 4th Character Class

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#95]
Use this guy as inspiration: 

![char5-bust.png](https://zube.io/files/enigmadragons/3a9a16ba3ef38c11483bcf9b585bc966-char5-bust.png)

**Comment by 0crat** [comment]
The job [#95](https://github.com/enigmadragons/projectneon/issues/95) assigned to @kazamaru[/z](https://www.0crat.com/u/kazamaru), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/26f8a811-4f1d-406b-9986-e1178f46ae2c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @kazamaru[/z](https://www.0crat.com/u/kazamaru) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @kazamaru[/z](https://www.0crat.com/u/kazamaru)

**Comment by 0crat** [comment]
The job [#95](https://github.com/enigmadragons/projectneon/issues/95) is now out of scope
