### ISSUE TITLE
Create Damage Numeric Visual Effect

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#99]
Should be attached to a character.
When the character is dealt damage, should appear above the character briefly, and then fade out after a bit.

https://www.giantbomb.com/damage-numbers/3015-2106/

**Comment by WhimsySoftware** [comment]
Now there is nothing in the project that would cause damage. Should I make a universal module, without binding to specific scripts?

**Comment by SilasReinagel** [comment]
@WhimsySoftware Just focus on the visual effect. 

We will wire in actual damage in a future ticket.

You may create any object you like for developing/debugging.
